### PR TITLE
Remove the menu settings in Cash

### PR DESCRIPTION
**Pull request by vendethiel**
Also fix the menu separators.

### CODE REVIEW

**Comment by MWE001** [comment]
Nice. I am curious to try this out. No more 3 menus for the same plugin? It defaults to all menu items in the ACP slide menu now?

**Comment by MWE001** [comment]
I'm not so sure this works right? I made all the changes verbatim and when I selected navbar in the config to no, the page went white on submit and won't come back. The only way to fix was uninstall and reinstall plugin.

**Comment by vendethiel** [comment]
I need to make sure it works. There was some wonky behavior in the navbar I tried to fix, but I had to fix it on a page-per-page basis. Might've been the wrong one...

**Comment by vendethiel** [comment]
Let me try with the top acp but no navbar.

**Pull request merged**
